# notify.yml
name: 'Send a message to Discord'
description: 'Send message to Discord'
inputs:
  message:  
    description: 'Message to send'
    required: true
  sender:  
    description: 'Who sent the message'
    required: false
    default: "GHA Pipeline"
runs:
  using: "composite"
  steps:
    - name: Read value
      run: |
        echo "::add-mask::$WEBHOOK"
        curl -s -H "Content-Type: application/json" -d "{\"username\": \"${{ inputs.sender }}\", \"content\": \"${{ inputs.message }}\"}" $WEBHOOK
      shell: bash
