# run_tofu.yml
name: 'Run a Opentofu script'
description: 'Run a Opentofu script'
inputs:
  bucket:  
    description: 'Bucket to store statefile'
    required: true
  key:
    description: 'Statefile key path'
    required: true
  s3-host:
    description: 'Host and Port for S3 service'
    required: true
  backend-config-path:
    description: 'Path to store backend config'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Write backend config
      shell: bash
      run: |
        echo 'bucket = "${{ inputs.bucket }}"' > ${{ inputs.backend-config-path }}
        echo "key    = \"${{ inputs.key }}\"" >> ${{ inputs.backend-config-path }}
        echo 'region = "us-east-1"' >> ${{ inputs.backend-config-path }}
        echo 'skip_credentials_validation = true' >> ${{ inputs.backend-config-path }}
        echo 'skip_requesting_account_id = true' >> ${{ inputs.backend-config-path }}
        echo 'skip_metadata_api_check = true' >> ${{ inputs.backend-config-path }}
        echo 'skip_region_validation = true' >> ${{ inputs.backend-config-path }}
        echo 'use_path_style = true' >> ${{ inputs.backend-config-path }}
        echo 'endpoints = {' >> ${{ inputs.backend-config-path }}
        echo "  s3 = \"${{ inputs.s3-host }}\"" >> ${{ inputs.backend-config-path }}
        echo -n '}' >> ${{ inputs.backend-config-path }}
