# cleanup.yml
name: 'Cleanup workspace'
description: 'Cleanup workspace'
runs:
  using: "composite"
  steps:
    - name: Cleanup workspace
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
      shell: bash
