# run_tofu.yml
name: 'Run a Opentofu script'
description: 'Run a Opentofu script'
inputs:
  script-path:  
    description: 'Message to send'
    required: true
  config-path:
    description: 'Path to AWS config file'
    required: true
  credentials-path:
    description: 'Path to AWS credentials file'
    required: true
  apply:
    description: 'Apply script. Default Plan'
    required: true
  backend-path:
    description: 'Path to backend configuration file'
    required: true
    default: ""
  additional-params:
    description: 'Additional parameters for Opentofu call'
    required: false
    
runs:
  using: "composite"
  steps:
    - name: Setup Opentofu
      uses: opentofu/setup-opentofu@v1.0.3
      with:
        tofu_version: 1.7.0
    - name: Do Opentofu stuff
      shell: bash
      run: |
        export AWS_CONFIG_FILE=${{ inputs.config-path }}
        export AWS_SHARED_CREDENTIALS_FILE=${{ inputs.credentials-path }}
        WORKDIR=${{ inputs.script-path }}
        BACKEND_CONFIG=${{ inputs.backend-path }}
        tofu -chdir=$WORKDIR init -backend-config=${{ inputs.backend-path }}
        echo ========working path===========================
        echo $WORKDIR
        echo =============ls ===========================0
        ls -l $WORKDIR
        if [[ ${{ inputs.apply }} == "apply" ]]
        then
          tofu -chdir=$WORKDIR apply -auto-approve ${{inputs.additional-params}}
        else
          tofu -chdir=$WORKDIR plan ${{inputs.additional-params}}
        fi
        echo =============== done ====================0
